# Generated by Django 3.2.13 on 2022-05-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_date', models.DateField()),
                ('file', models.FileField(upload_to='upload/files/')),
                ('title', models.TextField(max_length=100)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
