# Generated by Django 3.2.13 on 2022-05-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.DurationField(blank=10),
        ),
        migrations.AlterField(
            model_name='content',
            name='specific_date',
            field=models.DateField(blank=True),
        ),
    ]
