# Generated by Django 3.2.13 on 2022-05-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
