version: "3.9"
services:
  bas-viewer:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=shouldchangeme
      - DJANGO_SUPERUSER_PASSWORD=lolimagine
      - DJANGO_SUPERUSER_EMAIL=admin@example.com